version: '3'

services:
  app:
    # image: ghcr.io/nebucatnetzer/meta-search/app
    image: localhost/zweili-search-app:latest
    volumes:
      - /var/lib/zweili_search:/var/lib/zweili_search/

  nginx:
    # image: ghcr.io/nebucatnetzer/meta-search/ngix
    image: localhost/zweili-search-nginx:latest
    ports:
      - 8000:80
    volumes:
      - /var/lib/zweili_search/static:/var/lib/zweili_search/static
