# Generated by Django 4.2.23 on 2025-07-20 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_blockeddomain_blocklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocklist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocklist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
