# Generated by Django 4.2.23 on 2025-10-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_alter_blocklist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocklist",
            name="blocked_domains",
        ),
        migrations.RemoveField(
            model_name="blocklist",
            name="user",
        ),
        migrations.DeleteModel(
            name="BlockedDomain",
        ),
        migrations.DeleteModel(
            name="BlockList",
        ),
    ]
