# Generated by Django 4.2.23 on 2025-10-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_remove_blocklist_blocked_domains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchuser",
            name="default_search_engine_url",
            field=models.URLField(
                default="https://duckduckgo.com/?q={query}",
                help_text="Default search engine URL template. Use {query} as placeholder for the search query.",
                max_length=500,
            ),
        ),
    ]
