# Generated by Django 4.2.23 on 2025-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_alter_searchuser_default_search_engine_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchuser",
            name="default_search_engine_url",
            field=models.URLField(
                default="https://searxng.zweili.org/search?q={query}",
                help_text="Default search engine URL template. Use {query} as placeholder.",
                max_length=500,
            ),
        ),
    ]
