on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "test-ci" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-app-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: wimpysworld/nothing-but-nix@main
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v31.3.0
        with:
          extra_nix_config: "extra-platforms = aarch64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build app image
        run: ./tooling/bin/build-app-image.sh

  build-nginx-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31.3.0
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build nginx image
        run: ./tooling/bin/build-nginx-image.sh
